# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0006_auto_20161212_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vend',
            name='subscriber_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
