# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0007_auto_20170515_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='voucher_type',
            field=models.CharField(choices=[(b'', b'Select Type'), (b'STD', b'Standard'), (b'INS', b'Instant')], default='STD', max_length=3),
            preserve_default=False,
        ),
    ]
