# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0008_vendor_voucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vend',
            name='voucher_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
